### ISSUE TITLE
chprog.py - "Configuration not set" Error

### ISSUE THREAD

**Issue by TomatoCube18** [wagiminator/MCU-Flash-Tools#3]
Dear Stefan,

Thanks a lot for all your wonderful sharing. 

I was using the "chprog.py" script for programming CH32X033 chip on a M1 MacOS and bump into the following error. 
"Configuration not set", it could very well be a local issue on my setup, so might not be something of a concern.

<img width="570" alt="Screenshot 2024-04-02 at 3 17 36 PM" src="https://github.com/wagiminator/MCU-Flash-Tools/assets/47109215/4424beb7-1aef-4076-96c9-843ad9905e29">

I manage to get the programer to work for me by adding the following
"self.dev.set_configuration()" to line 89. (Sorry not a Python programmer myself)

<img width="578" alt="Screenshot 2024-04-02 at 3 17 43 PM" src="https://github.com/wagiminator/MCU-Flash-Tools/assets/47109215/fdfc2022-9ccb-4270-9c6a-56d164896e92">

Hope it would come in handy for anyone facing the same issue.

**Comment by wagiminator** [comment]
Thank you! I'll test whether the addition causes any problems with Linux and if not, I'll add the line by default.

**Comment by TomatoCube18** [comment]
Tested Version v2.4 of the chprog.py on the Mac.
The code is Working wonderfully. 

Thanks.
