### ISSUE TITLE
CH592 support?

### ISSUE THREAD

**Issue by KenjutsuGH** [wagiminator/MCU-Flash-Tools#4]
Good day

Thank you for your hard work on making these flash tools. Any plans to support the CH592?

**Comment by wagiminator** [comment]
I have added support for the CH592, among others, to chprog. Since I do not have the chip myself, it is untested.

**Comment by KenjutsuGH** [comment]
Awesome! Thank you, I tested it with a Weact CH592 and flashing a .bin file works flawlessly

**Comment by biemster** [comment]
Not sure if I should continue on this issue or open a new one, but when I flash my ch592 with chprog it seems to all work fine (chip id and flash verification succeed), but the firmware does not run. Also not after a power cycle.
When I flash this same fw with wchisp it does work, so it's definitely a flasher issue it seems.

**Comment by KenjutsuGH** [comment]
Only .bin files work. It will flash the other types, but the firmware does not run.

**Comment by biemster** [comment]
> Only .bin files work. It will flash the other types, but the firmware does not run.

Yes indeed, makes sense actually. I just did not read the instructions well enough (sorry for the noise).

**Comment by wagiminator** [comment]
Oh yes, when I have some time again, I will add support for .hex and .elf.

**Comment by martinberlin** [comment]
Adding .hex support will be great! So far when building in Mountriver I'm doing this in linux to convert the hex file into **bin**


     objcopy --input-target=ihex --output-target=binary source.hex target.bin
